name: Combine EPGs

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  combine-epgs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Run EPG combiner script
      run: |
        python combine_epgs.py

    - name: Commit and push combined EPG
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        git add combined_epg.xml
        git commit -m "Update combined EPG" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
